import torch
import numpy as np
import pickle
from music21 import instrument, note, chord, stream
from model import MusicLSTM

def generate():
    # Load data needed for generation
    with open('processed_data/mapping.pkl', 'rb') as f:
        note_to_int = pickle.load(f)
        
    int_to_note = {number: note for note, number in note_to_int.items()}
    n_vocab = len(note_to_int)
    
    # Load the model and weights
    model = MusicLSTM(n_vocab)
    model.load_state_dict(torch.load('models/final_model.pth', map_location=torch.device('cpu')))
    model.eval()
    
    # Load input sequences to get a seed
    network_input = np.load('processed_data/network_input.npy')
    
    # Pick a random seed
    start = np.random.randint(0, len(network_input)-1)
    pattern = network_input[start].tolist()
    
    prediction_output = []

    # Generate 500 notes
    print("Generating music...")
    for note_index in range(500):
        prediction_input = torch.tensor([pattern]).long()
        
        with torch.no_grad():
            output = model(prediction_input)
            # Use softmax to get probabilities
            probabilities = torch.nn.functional.softmax(output, dim=1).numpy()[0]
            
            # Sample from the distribution instead of just picking argmax for variety
            prediction = np.random.choice(len(probabilities), p=probabilities)
            
            result = int_to_note[prediction]
            prediction_output.append(result)

            pattern.append(prediction)
            pattern = pattern[1:len(pattern)]

    create_midi(prediction_output)

def create_midi(prediction_output):
    """ convert the output from the prediction to notes and create a midi file
        from the notes """
    offset = 0
    output_notes = []

    # create note and chord objects based on the values generated by the model
    for pattern in prediction_output:
        # pattern is a chord
        if ('.' in pattern) or pattern.isdigit():
            notes_in_chord = pattern.split('.')
            notes = []
            for current_note in notes_in_chord:
                new_note = note.Note(int(current_note))
                new_note.storedInstrument = instrument.Piano()
                notes.append(new_note)
            new_chord = chord.Chord(notes)
            new_chord.offset = offset
            output_notes.append(new_chord)
        # pattern is a note
        else:
            new_note = note.Note(pattern)
            new_note.offset = offset
            new_note.storedInstrument = instrument.Piano()
            output_notes.append(new_note)

        # increase offset each iteration so that notes do not stack
        offset += 0.5

    midi_stream = stream.Stream(output_notes)
    midi_stream.write('midi', fp='output/test_output.mid')
    print("Generation complete. Saved to output/test_output.mid")

if __name__ == '__main__':
    generate()
